name: Build osu-tracker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-latest]
        build_type: [Release]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: List files in osu-tracker directory
        run: ls -R ${{ github.workspace }}/osu-tracker

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Configure
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/osu-tracker/CMakeLists.txt'
          configurePreset: '${{ matrix.os }}-${{ matrix.build_type }}'

      - name: Build
        uses: lukka/run-cmake@v10
        with:
          buildPreset: '${{ matrix.os }}-${{ matrix.build_type }}'
