name: Build osu-tracker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-latest]
        build_type: [release, debug]
    name: ${{ matrix.os == 'ubuntu-22.04' && 'linux' || matrix.os == 'windows-latest' && 'win' || matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: List files in osu-tracker directory
        run: ls -R ${{ github.workspace }}/osu-tracker

      - name: Install CMake
        uses: lukka/get-cmake@v4.0.1

      - name: Configure
        uses: lukka/run-cmake@v10.8
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/osu-tracker/CMakeLists.txt'
          configurePreset: 'x86-${{ matrix.build_type }}-${{ matrix.os }}'

      - name: Build
        uses: lukka/run-cmake@v10
        with:
          buildPreset: 'x86-${{ matrix.build_type }}-${{ matrix.os }}'
